namespace BetsKiller.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ReorganizedTableTeamsNBA : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.TeamsNBA", "GamesInSeason", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothAvgPoints", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothAvgAssists", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothAvgRebounds", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothAvgBlocks", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothAvgFouls", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothAvgTurnovers", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeAvgPoints", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeAvgAssists", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeAvgRebounds", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeAvgBlocks", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeAvgFouls", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeAvgTurnovers", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayAvgPoints", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayAvgAssists", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayAvgRebounds", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayAvgBlocks", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayAvgFouls", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayAvgTurnovers", c => c.String());
            DropColumn("dbo.TeamsNBA", "BothTeamFG");
            DropColumn("dbo.TeamsNBA", "BothTeamFGP");
            DropColumn("dbo.TeamsNBA", "BothTeamFT");
            DropColumn("dbo.TeamsNBA", "BothTeamFTP");
            DropColumn("dbo.TeamsNBA", "BothTeam3s");
            DropColumn("dbo.TeamsNBA", "BothTeam3sP");
            DropColumn("dbo.TeamsNBA", "BothTeamBLKS");
            DropColumn("dbo.TeamsNBA", "BothTeamORBND");
            DropColumn("dbo.TeamsNBA", "BothTeamRBND");
            DropColumn("dbo.TeamsNBA", "BothTeamFouls");
            DropColumn("dbo.TeamsNBA", "BothTeamAST");
            DropColumn("dbo.TeamsNBA", "BothTeamTOvers");
            DropColumn("dbo.TeamsNBA", "BothTeamQ1");
            DropColumn("dbo.TeamsNBA", "BothTeamQ2");
            DropColumn("dbo.TeamsNBA", "BothTeamQ3");
            DropColumn("dbo.TeamsNBA", "BothTeamQ4");
            DropColumn("dbo.TeamsNBA", "BothTeamFinal");
            DropColumn("dbo.TeamsNBA", "BothOppFG");
            DropColumn("dbo.TeamsNBA", "BothOppFGP");
            DropColumn("dbo.TeamsNBA", "BothOppFT");
            DropColumn("dbo.TeamsNBA", "BothOppFTP");
            DropColumn("dbo.TeamsNBA", "BothOpp3s");
            DropColumn("dbo.TeamsNBA", "BothOpp3sP");
            DropColumn("dbo.TeamsNBA", "BothOppBLKS");
            DropColumn("dbo.TeamsNBA", "BothOppORBND");
            DropColumn("dbo.TeamsNBA", "BothOppRBND");
            DropColumn("dbo.TeamsNBA", "BothOppFouls");
            DropColumn("dbo.TeamsNBA", "BothOppAST");
            DropColumn("dbo.TeamsNBA", "BothOppTOvers");
            DropColumn("dbo.TeamsNBA", "BothOppQ1");
            DropColumn("dbo.TeamsNBA", "BothOppQ2");
            DropColumn("dbo.TeamsNBA", "BothOppQ3");
            DropColumn("dbo.TeamsNBA", "BothOppQ4");
            DropColumn("dbo.TeamsNBA", "BothOppFinal");
            DropColumn("dbo.TeamsNBA", "BothFGA");
            DropColumn("dbo.TeamsNBA", "BothFGM");
            DropColumn("dbo.TeamsNBA", "BothTPA");
            DropColumn("dbo.TeamsNBA", "BothTPM");
            DropColumn("dbo.TeamsNBA", "BothTO");
            DropColumn("dbo.TeamsNBA", "BothAST");
            DropColumn("dbo.TeamsNBA", "BothFGP");
            DropColumn("dbo.TeamsNBA", "BothTPP");
            DropColumn("dbo.TeamsNBA", "BothFTP");
            DropColumn("dbo.TeamsNBA", "BothPFT");
            DropColumn("dbo.TeamsNBA", "BothPTP");
            DropColumn("dbo.TeamsNBA", "BothWP");
            DropColumn("dbo.TeamsNBA", "HomeTeamFG");
            DropColumn("dbo.TeamsNBA", "HomeTeamFGP");
            DropColumn("dbo.TeamsNBA", "HomeTeamFT");
            DropColumn("dbo.TeamsNBA", "HomeTeamFTP");
            DropColumn("dbo.TeamsNBA", "HomeTeam3s");
            DropColumn("dbo.TeamsNBA", "HomeTeam3sP");
            DropColumn("dbo.TeamsNBA", "HomeTeamBLKS");
            DropColumn("dbo.TeamsNBA", "HomeTeamORBND");
            DropColumn("dbo.TeamsNBA", "HomeTeamRBND");
            DropColumn("dbo.TeamsNBA", "HomeTeamFouls");
            DropColumn("dbo.TeamsNBA", "HomeTeamAST");
            DropColumn("dbo.TeamsNBA", "HomeTeamTOvers");
            DropColumn("dbo.TeamsNBA", "HomeTeamQ1");
            DropColumn("dbo.TeamsNBA", "HomeTeamQ2");
            DropColumn("dbo.TeamsNBA", "HomeTeamQ3");
            DropColumn("dbo.TeamsNBA", "HomeTeamQ4");
            DropColumn("dbo.TeamsNBA", "HomeTeamFinal");
            DropColumn("dbo.TeamsNBA", "HomeOppFG");
            DropColumn("dbo.TeamsNBA", "HomeOppFGP");
            DropColumn("dbo.TeamsNBA", "HomeOppFT");
            DropColumn("dbo.TeamsNBA", "HomeOppFTP");
            DropColumn("dbo.TeamsNBA", "HomeOpp3s");
            DropColumn("dbo.TeamsNBA", "HomeOpp3sP");
            DropColumn("dbo.TeamsNBA", "HomeOppBLKS");
            DropColumn("dbo.TeamsNBA", "HomeOppORBND");
            DropColumn("dbo.TeamsNBA", "HomeOppRBND");
            DropColumn("dbo.TeamsNBA", "HomeOppFouls");
            DropColumn("dbo.TeamsNBA", "HomeOppAST");
            DropColumn("dbo.TeamsNBA", "HomeOppTOvers");
            DropColumn("dbo.TeamsNBA", "HomeOppQ1");
            DropColumn("dbo.TeamsNBA", "HomeOppQ2");
            DropColumn("dbo.TeamsNBA", "HomeOppQ3");
            DropColumn("dbo.TeamsNBA", "HomeOppQ4");
            DropColumn("dbo.TeamsNBA", "HomeOppFinal");
            DropColumn("dbo.TeamsNBA", "HomeFGA");
            DropColumn("dbo.TeamsNBA", "HomeFGM");
            DropColumn("dbo.TeamsNBA", "HomeTPA");
            DropColumn("dbo.TeamsNBA", "HomeTPM");
            DropColumn("dbo.TeamsNBA", "HomeTO");
            DropColumn("dbo.TeamsNBA", "HomeAST");
            DropColumn("dbo.TeamsNBA", "HomeFGP");
            DropColumn("dbo.TeamsNBA", "HomeTPP");
            DropColumn("dbo.TeamsNBA", "HomeFTP");
            DropColumn("dbo.TeamsNBA", "HomePFT");
            DropColumn("dbo.TeamsNBA", "HomePTP");
            DropColumn("dbo.TeamsNBA", "HomeWP");
            DropColumn("dbo.TeamsNBA", "AwayTeamFG");
            DropColumn("dbo.TeamsNBA", "AwayTeamFGP");
            DropColumn("dbo.TeamsNBA", "AwayTeamFT");
            DropColumn("dbo.TeamsNBA", "AwayTeamFTP");
            DropColumn("dbo.TeamsNBA", "AwayTeam3s");
            DropColumn("dbo.TeamsNBA", "AwayTeam3sP");
            DropColumn("dbo.TeamsNBA", "AwayTeamBLKS");
            DropColumn("dbo.TeamsNBA", "AwayTeamORBND");
            DropColumn("dbo.TeamsNBA", "AwayTeamRBND");
            DropColumn("dbo.TeamsNBA", "AwayTeamFouls");
            DropColumn("dbo.TeamsNBA", "AwayTeamAST");
            DropColumn("dbo.TeamsNBA", "AwayTeamTOvers");
            DropColumn("dbo.TeamsNBA", "AwayTeamQ1");
            DropColumn("dbo.TeamsNBA", "AwayTeamQ2");
            DropColumn("dbo.TeamsNBA", "AwayTeamQ3");
            DropColumn("dbo.TeamsNBA", "AwayTeamQ4");
            DropColumn("dbo.TeamsNBA", "AwayTeamFinal");
            DropColumn("dbo.TeamsNBA", "AwayOppFG");
            DropColumn("dbo.TeamsNBA", "AwayOppFGP");
            DropColumn("dbo.TeamsNBA", "AwayOppFT");
            DropColumn("dbo.TeamsNBA", "AwayOppFTP");
            DropColumn("dbo.TeamsNBA", "AwayOpp3s");
            DropColumn("dbo.TeamsNBA", "AwayOpp3sP");
            DropColumn("dbo.TeamsNBA", "AwayOppBLKS");
            DropColumn("dbo.TeamsNBA", "AwayOppORBND");
            DropColumn("dbo.TeamsNBA", "AwayOppRBND");
            DropColumn("dbo.TeamsNBA", "AwayOppFouls");
            DropColumn("dbo.TeamsNBA", "AwayOppAST");
            DropColumn("dbo.TeamsNBA", "AwayOppTOvers");
            DropColumn("dbo.TeamsNBA", "AwayOppQ1");
            DropColumn("dbo.TeamsNBA", "AwayOppQ2");
            DropColumn("dbo.TeamsNBA", "AwayOppQ3");
            DropColumn("dbo.TeamsNBA", "AwayOppQ4");
            DropColumn("dbo.TeamsNBA", "AwayOppFinal");
            DropColumn("dbo.TeamsNBA", "AwayFGA");
            DropColumn("dbo.TeamsNBA", "AwayFGM");
            DropColumn("dbo.TeamsNBA", "AwayTPA");
            DropColumn("dbo.TeamsNBA", "AwayTPM");
            DropColumn("dbo.TeamsNBA", "AwayTO");
            DropColumn("dbo.TeamsNBA", "AwayAST");
            DropColumn("dbo.TeamsNBA", "AwayFGP");
            DropColumn("dbo.TeamsNBA", "AwayTPP");
            DropColumn("dbo.TeamsNBA", "AwayFTP");
            DropColumn("dbo.TeamsNBA", "AwayPFT");
            DropColumn("dbo.TeamsNBA", "AwayPTP");
            DropColumn("dbo.TeamsNBA", "AwayWP");
        }
        
        public override void Down()
        {
            AddColumn("dbo.TeamsNBA", "AwayWP", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayPTP", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayPFT", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayFTP", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTPP", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayFGP", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayAST", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTO", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTPM", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTPA", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayFGM", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayFGA", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppFinal", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppQ4", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppQ3", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppQ2", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppQ1", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppTOvers", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppAST", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppFouls", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppRBND", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppORBND", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppBLKS", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOpp3sP", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOpp3s", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppFTP", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppFT", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppFGP", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayOppFG", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamFinal", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamQ4", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamQ3", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamQ2", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamQ1", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamTOvers", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamAST", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamFouls", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamRBND", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamORBND", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamBLKS", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeam3sP", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeam3s", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamFTP", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamFT", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamFGP", c => c.String());
            AddColumn("dbo.TeamsNBA", "AwayTeamFG", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeWP", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomePTP", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomePFT", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeFTP", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTPP", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeFGP", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeAST", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTO", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTPM", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTPA", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeFGM", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeFGA", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppFinal", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppQ4", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppQ3", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppQ2", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppQ1", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppTOvers", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppAST", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppFouls", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppRBND", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppORBND", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppBLKS", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOpp3sP", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOpp3s", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppFTP", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppFT", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppFGP", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeOppFG", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamFinal", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamQ4", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamQ3", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamQ2", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamQ1", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamTOvers", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamAST", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamFouls", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamRBND", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamORBND", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamBLKS", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeam3sP", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeam3s", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamFTP", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamFT", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamFGP", c => c.String());
            AddColumn("dbo.TeamsNBA", "HomeTeamFG", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothWP", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothPTP", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothPFT", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothFTP", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTPP", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothFGP", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothAST", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTO", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTPM", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTPA", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothFGM", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothFGA", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppFinal", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppQ4", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppQ3", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppQ2", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppQ1", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppTOvers", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppAST", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppFouls", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppRBND", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppORBND", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppBLKS", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOpp3sP", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOpp3s", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppFTP", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppFT", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppFGP", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothOppFG", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamFinal", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamQ4", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamQ3", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamQ2", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamQ1", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamTOvers", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamAST", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamFouls", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamRBND", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamORBND", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamBLKS", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeam3sP", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeam3s", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamFTP", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamFT", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamFGP", c => c.String());
            AddColumn("dbo.TeamsNBA", "BothTeamFG", c => c.String());
            DropColumn("dbo.TeamsNBA", "AwayAvgTurnovers");
            DropColumn("dbo.TeamsNBA", "AwayAvgFouls");
            DropColumn("dbo.TeamsNBA", "AwayAvgBlocks");
            DropColumn("dbo.TeamsNBA", "AwayAvgRebounds");
            DropColumn("dbo.TeamsNBA", "AwayAvgAssists");
            DropColumn("dbo.TeamsNBA", "AwayAvgPoints");
            DropColumn("dbo.TeamsNBA", "HomeAvgTurnovers");
            DropColumn("dbo.TeamsNBA", "HomeAvgFouls");
            DropColumn("dbo.TeamsNBA", "HomeAvgBlocks");
            DropColumn("dbo.TeamsNBA", "HomeAvgRebounds");
            DropColumn("dbo.TeamsNBA", "HomeAvgAssists");
            DropColumn("dbo.TeamsNBA", "HomeAvgPoints");
            DropColumn("dbo.TeamsNBA", "BothAvgTurnovers");
            DropColumn("dbo.TeamsNBA", "BothAvgFouls");
            DropColumn("dbo.TeamsNBA", "BothAvgBlocks");
            DropColumn("dbo.TeamsNBA", "BothAvgRebounds");
            DropColumn("dbo.TeamsNBA", "BothAvgAssists");
            DropColumn("dbo.TeamsNBA", "BothAvgPoints");
            DropColumn("dbo.TeamsNBA", "GamesInSeason");
        }
    }
}
